use crate::game::types::*;
// Filenames match the actual webp assets in /assets (case-sensitive on some hosts).

pub(super) fn build_character_defs() -> Vec<CharacterDef> {
    use Property::*;
    vec![
        CharacterDef {
            id: "meme_man".into(),
            name: "Meme Man".into(),
            sprite: "Meme_Man.webp".into(),
            cost: 90,
            might: 10,
            reflexes: 10,
            wisdom: 10,
            hp: 50,
            properties: vec![],
        },
        CharacterDef {
            id: "picardia".into(),
            name: "Picardia".into(),
            sprite: "picardia.webp".into(),
            cost: 70,
            might: 12,
            reflexes: 15,
            wisdom: 5,
            hp: 25,
            properties: vec![],
        },
        CharacterDef {
            id: "omniscronchulon".into(),
            name: "Omniscronchulon".into(),
            sprite: "omniscronchulon.webp".into(),
            cost: 160,
            might: 12,
            reflexes: 15,
            wisdom: 5,
            hp: 25,
            properties: vec![MeleeCleave { count: 2 }],
        },
        CharacterDef {
            id: "omegascronchulon".into(),
            name: "Omegascronchulon".into(),
            sprite: "omegascronchulon.webp".into(),
            cost: 160,
            might: 12,
            reflexes: 15,
            wisdom: 5,
            hp: 25,
            properties: vec![FourHanded],
        },
        CharacterDef {
            id: "azul_picardia".into(),
            name: "Azul Picardia".into(),
            sprite: "azul_picardia.webp".into(),
            cost: 100,
            might: 12,
            reflexes: 10,
            wisdom: 5,
            hp: 25,
            properties: vec![FreezeOnHit {
                sprite: "ice.webp".into(),
            }],
        },
        CharacterDef {
            id: "lemen".into(),
            name: "Lemen".into(),
            sprite: "Lemen_man.webp".into(),
            cost: 110,
            might: 3,
            reflexes: 10,
            wisdom: 8,
            hp: 20,
            properties: vec![Ranged {
                projectile: "lemon.webp".into(),
            }],
        },
        CharacterDef {
            id: "elephoont".into(),
            name: "Elephoont".into(),
            sprite: "elephoont.webp".into(),
            cost: 160,
            might: 15,
            reflexes: 9,
            wisdom: 30,
            hp: 75,
            properties: vec![BuffFormationFront {
                might: 3,
                reflexes: 3,
                wisdom: 3,
                hp: 3,
            }],
        },
        CharacterDef {
            id: "isoceles".into(),
            name: "Isoceles".into(),
            sprite: "Isosceles.webp".into(),
            cost: 120,
            might: 5,
            reflexes: 20,
            wisdom: 5,
            hp: 1,
            properties: vec![Ranged {
                projectile: "octahedron.webp".into(),
            }],
        },
        CharacterDef {
            id: "vegetal".into(),
            name: "Vegetal".into(),
            sprite: "vegetal.webp".into(),
            cost: 50,
            might: 8,
            reflexes: 12,
            wisdom: 1,
            hp: 20,
            properties: vec![SummonOnEnemyDeath {
                species: "vegetal".into(),
            }],
        },
        CharacterDef {
            id: "dark_vegetal".into(),
            name: "Dark Vegetal".into(),
            sprite: "dark_vegetal.webp".into(),
            cost: 50,
            might: 8,
            reflexes: 12,
            wisdom: 1,
            hp: 20,
            properties: vec![SummonOnAllyDeath {
                species: "dark_vegetal".into(),
            }],
        },
        CharacterDef {
            id: "redchilli".into(),
            name: "Red Chilli".into(),
            sprite: "redchilli.webp".into(),
            cost: 70,
            might: 10,
            reflexes: 10,
            wisdom: 5,
            hp: 20,
            properties: vec![DamageEnemyOnDeath {
                might_multiplier: 2,
            }],
        },
        CharacterDef {
            id: "greenchilli".into(),
            name: "Green Chilli".into(),
            sprite: "greenchilli.webp".into(),
            cost: 90,
            might: 10,
            reflexes: 10,
            wisdom: 5,
            hp: 20,
            properties: vec![TeamStatsOnDeath { amount: 3 }],
        },
        CharacterDef {
            id: "orang".into(),
            name: "Orang".into(),
            sprite: "orang.webp".into(),
            cost: 90,
            might: 6,
            reflexes: 10,
            wisdom: 10,
            hp: 80,
            properties: vec![],
        },
        CharacterDef {
            id: "gren".into(),
            name: "Gren".into(),
            sprite: "gren.webp".into(),
            cost: 150,
            might: 5,
            reflexes: 5,
            wisdom: 10,
            hp: 60,
            properties: vec![Healer],
        },
    ]
}

//@item -- when items are added, expand here. Keep ids stable.

pub(super) fn build_item_defs() -> Vec<ItemDef> {
    vec![
        ItemDef {
            id: "steve_hat".into(),
            name: "Steve Hat".into(),
            sprite: "stevehat.png".into(),
            cost: 100,
            slot: GearSlot::Hat,
            properties: vec![Property::StatBonus {
                might: 10,
                reflexes: 0,
                wisdom: 0,
                hp: 0,
            }],
        },
        ItemDef {
            id: "noggin_hat".into(),
            name: "Noggin".into(),
            sprite: "Noggin.webp".into(),
            cost: 30,
            slot: GearSlot::Hat,
            properties: vec![Property::StatBonus {
                might: 0,
                reflexes: 0,
                wisdom: 0,
                hp: 25,
            }],
        },
        ItemDef {
            id: "fedora_hat".into(),
            name: "Fedora".into(),
            sprite: "fedora.png".into(),
            cost: 50,
            slot: GearSlot::Hat,
            properties: vec![Property::StatBonus {
                might: 0,
                reflexes: 0,
                wisdom: 10,
                hp: 0,
            }],
        },
        ItemDef {
            id: "speed_hat".into(),
            name: "Speed".into(),
            sprite: "speed.webp".into(),
            cost: 70,
            slot: GearSlot::Hat,
            properties: vec![Property::StatBonus {
                might: 0,
                reflexes: 5,
                wisdom: 0,
                hp: 0,
            }],
        },
        ItemDef {
            id: "viking_hat".into(),
            name: "Viking Hat".into(),
            sprite: "hatviking.png".into(),
            cost: 40,
            slot: GearSlot::Hat,
            properties: vec![Property::MightOnAllyDeath { might: 5 }],
        },
        ItemDef {
            id: "hard_hat".into(),
            name: "Hard Hat".into(),
            sprite: "hardhat.png".into(),
            cost: 40,
            slot: GearSlot::Hat,
            properties: vec![Property::Armour { value: 3 }],
        },
        ItemDef {
            id: "rice_hat".into(),
            name: "Rice Hat".into(),
            sprite: "hatrice.png".into(),
            cost: 80,
            slot: GearSlot::Hat,
            properties: vec![Property::CritStrike { chance_percent: 50 }],
        },
        ItemDef {
            id: "pope_hat".into(),
            name: "Pope Hat".into(),
            sprite: "hatpope.png".into(),
            cost: 100,
            slot: GearSlot::Hat,
            properties: vec![Property::ReviveOnce],
        },
        ItemDef {
            id: "hussar_hat".into(),
            name: "Hussar Hat".into(),
            sprite: "hathussar.png".into(),
            cost: 110,
            slot: GearSlot::Hat,
            properties: vec![Property::StatsOnAllyDeath {
                might: 3,
                reflexes: 3,
                wisdom: 3,
                hp: 3,
            }],
        },
        ItemDef {
            id: "vlad_hat".into(),
            name: "Vlad Hat".into(),
            sprite: "vlad.png".into(),
            cost: 70,
            slot: GearSlot::Hat,
            properties: vec![Property::StatsOnKill {
                might: 3,
                reflexes: 3,
                wisdom: 3,
                hp: 3,
            }],
        },
        ItemDef {
            id: "propellor_hat".into(),
            name: "Propellor Hat".into(),
            sprite: "propellor.png".into(),
            cost: 100,
            slot: GearSlot::Hat,
            properties: vec![Property::ReviveAtBackOnce],
        },
        ItemDef {
            id: "captains_hat".into(),
            name: "Captain's Hat".into(),
            sprite: "captainshat.png".into(),
            cost: 50,
            slot: GearSlot::Hat,
            properties: vec![Property::StatsPerLivingAlly { amount: 1 }],
        },
        ItemDef {
            id: "pickle_rick".into(),
            name: "Hotdog Harry".into(),
            sprite: "hotdog_harry.png".into(),
            cost: 40,
            slot: GearSlot::Hand,
            properties: vec![Property::StatBonus {
                might: 5,
                reflexes: 0,
                wisdom: 0,
                hp: 0,
            }],
        },
        ItemDef {
            id: "bread".into(),
            name: "Bread".into(),
            sprite: "bread.webp".into(),
            cost: 30,
            slot: GearSlot::Hand,
            properties: vec![Property::StatBonus {
                might: 0,
                reflexes: 0,
                wisdom: 0,
                hp: 20,
            }],
        },
        ItemDef {
            id: "spellbook".into(),
            name: "Spellbook".into(),
            sprite: "spellbook.png".into(),
            cost: 70,
            slot: GearSlot::Hand,
            properties: vec![Property::StatBonus {
                might: 0,
                reflexes: 0,
                wisdom: 5,
                hp: 0,
            }],
        },
        ItemDef {
            id: "spear".into(),
            name: "Spear".into(),
            sprite: "spear.png".into(),
            cost: 90,
            slot: GearSlot::Hand,
            properties: vec![
                Property::StatBonus {
                    might: 5,
                    reflexes: 0,
                    wisdom: 0,
                    hp: 0,
                },
                Property::MeleeFromSecond,
            ],
        },
        ItemDef {
            id: "kunai".into(),
            name: "Kunai".into(),
            sprite: "kunai.png".into(),
            cost: 70,
            slot: GearSlot::Hand,
            properties: vec![Property::StatBonus {
                might: 0,
                reflexes: 5,
                wisdom: 0,
                hp: 0,
            }],
        },
        ItemDef {
            id: "flamesword".into(),
            name: "Flamesword".into(),
            sprite: "flamesword.png".into(),
            cost: 200,
            slot: GearSlot::Hand,
            properties: vec![Property::MeleeCleaveBonus { plus: 1 }],
        },
        ItemDef {
            id: "darkblade".into(),
            name: "Darkblade".into(),
            sprite: "darkblade.png".into(),
            cost: 80,
            slot: GearSlot::Hand,
            properties: vec![Property::StatsOnKill {
                might: 3,
                reflexes: 3,
                wisdom: 3,
                hp: 3,
            }],
        },
        ItemDef {
            id: "shield".into(),
            name: "Shield".into(),
            sprite: "shield.webp".into(),
            cost: 40,
            slot: GearSlot::Hand,
            properties: vec![Property::Armour { value: 3 }],
        },
        ItemDef {
            id: "winterstaff".into(),
            name: "Winter Staff".into(),
            sprite: "winterstaff.png".into(),
            cost: 100,
            slot: GearSlot::Hand,
            properties: vec![Property::DebuffEnemyReflexes { amount: 3 }],
        },
        ItemDef {
            id: "fishstick".into(),
            name: "Fish Stick".into(),
            sprite: "fishstick.png".into(),
            cost: 50,
            slot: GearSlot::Hand,
            properties: vec![Property::DrainEnemyStatsOnHit { amount: 1 }],
        },
    ]
}
